schema_version: 1

context:
  version: 0.10.7

package:
  name: compiledb
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/source/c/compiledb/compiledb-${{ version }}.tar.gz
  sha256: 97752d8810b6977654a11a22cdc41bf6b71473bcdb5da312bc135f36d6af8271

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - compiledb=compiledb.cli:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - bashlex
    - click
    - python >=${{ python_min }}
    - shutilwhich

tests:
  - python:
      imports:
        - compiledb
        - compiledb.commands
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - compiledb --help

about:
  summary: Tool for generating Clang JSON Compilation Database files for make-based build systems.
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/nickdiego/compiledb

extra:
  recipe-maintainers:
    - marcelotrevisani
    - jsmolic
